ALTER TABLE `tbladdons` DROP FOREIGN KEY `tbladdons_ibfk_1`;
ALTER TABLE `tblserviceaddons` DROP FOREIGN KEY `tblserviceaddons_ibfk_3`;
ALTER TABLE `tbldownloads` DROP FOREIGN KEY `tbldownloads_ibfk_1`;

RENAME TABLE `tblaccounts` TO `ra_transactions`;
RENAME TABLE `tblactivitylog` TO `ra_systemlog`;
RENAME TABLE `tbladdonmodules` TO `ra_modules`;
RENAME TABLE `tbladminlog` TO `ra_adminlog`;
RENAME TABLE `tbladminperms` TO `ra_adminpriv`;
RENAME TABLE `tbladminroles` TO `ra_adminroles`;
RENAME TABLE `tbladmins` TO `ra_admin`;
RENAME TABLE `tblaffiliates` TO `ra_partners`;
RENAME TABLE `tblaffiliatesaccounts` TO `ra_partners_accounts`;
RENAME TABLE `tblaffiliateshistory` TO `ra_partners_history`;
RENAME TABLE `tblaffiliatespending` TO `ra_partners_spending`;
RENAME TABLE `tblaffiliateswithdrawals` TO `ra_partners_withdrawals`;
RENAME TABLE `tblbannedemails` TO `ra_bannedemails`;
RENAME TABLE `tblbannedips` TO `ra_bannedips`;
RENAME TABLE `tblcancelrequests` TO `ra_cancellations`;
RENAME TABLE `tblclientfields` TO `ra_user_fields`;
RENAME TABLE `tblclientfieldsvalues` TO `ra_user_fields_values`;
RENAME TABLE `tblclientgroups` TO `ra_user_group`;
RENAME TABLE `tblclients` TO `ra_user`;
RENAME TABLE `tblclientsfiles` TO `ra_user_files`;
RENAME TABLE `tblconfiguration` TO `ra_config`;
RENAME TABLE `tblcontacts` TO `ra_user_contacts`;
RENAME TABLE `tblcredit` TO `ra_transactions_credit`;
RENAME TABLE `tblcreditcards` TO `ra_user_gateway_details`;
RENAME TABLE `tblcurrencies` TO `ra_currency`;
RENAME TABLE `tblcustomerservices` TO `ra_catalog_user_sales`;
RENAME TABLE `tblcustomfields` TO `ra_services_fields`;
RENAME TABLE `tblcustomfieldsgrouplinks` TO `ra_services_fields_gl`;
RENAME TABLE `tblcustomfieldsgroupmembers` TO `ra_services_fields_gm`;
RENAME TABLE `tblcustomfieldsgroupnames` TO `ra_services_fields_gn`;
RENAME TABLE `tblcustomfieldslinks` TO `ra_services_fields_l`;
RENAME TABLE `tblcustomfieldsvalues` TO `ra_services_fields_v`;
RENAME TABLE `tblemails` TO `ra_user_mail`;
RENAME TABLE `tblemailtemplates` TO `ra_templates_mail`;
RENAME TABLE `tblgatewaylog` TO `ra_gateway_logs`;
RENAME TABLE `tblinvoiceitems` TO `ra_bill_lineitems`;
RENAME TABLE `tblinvoicepaymentmonitor` TO `ra_bill_payment_monitor`;
RENAME TABLE `tblinvoices` TO `ra_bills`;
RENAME TABLE `tblknowledgebase` TO `ra_kb`;
RENAME TABLE `tblknowledgebasecats` TO `ra_kb_cats`;
RENAME TABLE `tblknowledgebaselinks` TO `ra_kb_bl`;
RENAME TABLE `tblmodulelog` TO `ra_module_logs`;
RENAME TABLE `tblnetworkissues` TO `ra_system_status`;
RENAME TABLE `tblnotes` TO `ra_notes`;
RENAME TABLE `tblorders` TO `ra_orders`;
RENAME TABLE `tblorderstatuses` TO `ra_orders_status`;
RENAME TABLE `tblpaymentgatewaynames` TO `ra_modules_gateways_names`;
RENAME TABLE `tblpaymentgateways` TO `ra_modules_gateways`;
RENAME TABLE `tblpricing` TO `ra_catalog_pricebook`;
RENAME TABLE `tblpromotions` TO `ra_promos`;
RENAME TABLE `tblservergroups` TO `ra_integration_groups`;
RENAME TABLE `tblservergroupsrel` TO `ra_integration_group_links`;
RENAME TABLE `tblservers` TO `ra_integration`;
RENAME TABLE `tblserviceaddons` TO `ra_catalog_user_sales_addons`;
RENAME TABLE `tblserviceconfiggroups` TO `ra_catalog_user_sales_addons_groups`;
RENAME TABLE `tblserviceconfiglinks` TO `ra_catalog_user_sales_addons_links`;
RENAME TABLE `tblserviceconfigoptions` TO `ra_catalog_user_sales_addons_options`;
RENAME TABLE `tblserviceconfigoptionssub` TO `ra_catalog_user_sales_addons_options_subs`;
RENAME TABLE `tblservicegroups` TO `ra_catalog_groups`;
RENAME TABLE `tblservices` TO `ra_catalog`;
RENAME TABLE `tblservicetoservice` TO `ra_service2service`;
RENAME TABLE `tblsmstemplate` TO `ra_templates_sms`;
RENAME TABLE `tbltax` TO `ra_tax_rates`;
RENAME TABLE `tblticketdepartments` TO `ra_ticket_teams`;
RENAME TABLE `tblticketfeedback` TO `ra_ticket_feedback`;
RENAME TABLE `tblticketlog` TO `ra_ticket_log_link`;
RENAME TABLE `tblticketmaillog` TO `ra_ticket_log`;
RENAME TABLE `tblticketnotes` TO `ra_ticket_notes`;
RENAME TABLE `tblticketpredefinedcats` TO `ra_macro_categories`;
RENAME TABLE `tblticketpredefinedreplies` TO `ra_macro_categories_templates`;
RENAME TABLE `tblticketreplies` TO `ra_ticket_replies`;
RENAME TABLE `tbltickets` TO `ra_ticket`;
RENAME TABLE `tblticketstatuses` TO `ra_ticket_status`;
RENAME TABLE `tbltickettags` TO `ra_ticket_tags`;


DROP TABLE `migrations`;
DROP TABLE `mod_staffboard`;
DROP TABLE `tbladdons`;
DROP TABLE `tbladdontoservice`;
DROP TABLE `tbladresschecker`;
DROP TABLE `tblcalendar`;
DROP TABLE `tbldownloadcats`;
DROP TABLE `tbldownloads`;
DROP TABLE `tblticketbreaklines`;
DROP TABLE `tblticketspamfilters`;
DROP TABLE `tbltodolist`;
