---

- name: Install composer
  action: apt pkg={{item}} state=installed
  with_items:
    - composer

- name: composer deps per composer.json
  composer:
    command: install

- name: composer deps per composer.json (update)
  composer:
    command: update
