---

- name: Preconfigure postfix
  debconf:
    name: postfix
    question: postfix/relayhost
    value: localhost:1025
    vtype: string

- name: clone MailDev git repo
  git:
    repo: https://github.com/djfarrelly/MailDev
    dest: /var/www/maildev
  when: false # installed via npm below

- name: Add nodejs apt key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "1655A0AB68576280"

- name: Add nodejs apt repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_6.x stretch main
    state: present

- name: Install required packages
  action: apt pkg={{item}} state=installed
  with_items:
  - nodejs
  - postfix


- name: Install maildev via npm
  npm:
    name: maildev
    global: yes

- name: maildev systemd unit file
  template:
    src: templates/maildev.systemd.j2
    dest: /etc/systemd/system/maildev.service

- name: maildev systemd reload
  systemd:
    daemon_reload: yes
    name: maildev.service
    enabled: yes
    state: started

# vim: ai ts=2 sts=2 et sw=2
